name: linux
run-name: clang

on: [push]

jobs:
  ubuntu-clang:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - run: sudo apt install clang ninja-build cmake libopencv-dev

      - run: cmake -S . -B build -G Ninja
      - run: cmake --build build -j
