name: windows
run-name: msvc

on: [push]

jobs:
  server-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - name: Setup scoop
        uses: MinoruSekine/setup-scoop@v4

      - run: scoop install cmake

      - run: 7z x 3rdparty\opencv\bin\opencv_world4100.7z -o3rdparty\opencv\bin
      - run: 7z x 3rdparty\opencv\bin\opencv_world4100.7z -o3rdparty\opencv\bin
      
      - run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      - run: cmake --build build -j
