name: windows
run-name: msvc

on: [push]

jobs:
  server-msvc:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - name: Setup scoop
        uses: MinoruSekine/setup-scoop@v4

      - run: scoop install cmake
      
      - run: ./make.ps1
