name: windows
run-name: msvc

on: [push]

jobs:
  windowsserver:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6
        with:
          submodules: true

      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup scoop
        uses: MinoruSekine/setup-scoop@v4

      - run: scoop install cmake

      - run: Expand-Archive -Path '3rdparty\opencv\bin\opencv_world490d.zip' -DestinationPath '3rdparty\opencv\bin'
      - run: Expand-Archive -Path '3rdparty\opencv\lib\opencv_world490d.zip' -DestinationPath '3rdparty\opencv\lib'
      - run: cmake -S . -B build
      - run: cmake --build build -j
